### ISSUE TITLE
het commando 'vendor create' lijkt niets te doen 

### ISSUE THREAD

**Issue by inezhirs** [blue-10/Blue10CLI#15]
ik heb vanmorgen de nieuwe versie van Blue10CLI.exe gedownload en geprobeerd of ie werkt in onze omgeving. De 'credentials check' werkt, maar de opdracht 'vendor create' lijkt niets te doen.
Ik start een dos-prompt vanuit mijn cobol programma. Voor die credentials check had Yasen al iets aangepast in de exe, waardoor het ook werkte vanuit mijn cobol-programma. Mogelijk geldt die aanpassing alleen voor de credentials check? Ik geef deze opdracht in mijn cobol-programma:
Voor de credentials check:
C:\windows\system32\cmd.exe /C blue10cli.exe credentials check -o C:\Free2021\blue10\result.txt
Dat werkt; er wordt een result.txt aangemaakt; daar kan ik wat mee.
Voor het aanmaken van een crediteur is het:
C:\windows\system32\cmd.exe /C blue10cli.exe vendor create -a Freepack - API test -c (crediteur naam) --country NL --currency EUR --iban (iban) --ledger (grb-nummer) --vat (ob-nummer)  -o C:\free2021\blue10\result.txt
Er wordt geen crediteur aangemaakt in onze testadministratie, er wordt geen melding in de logfile weggeschreven en er wordt geen result.txt aangemaakt. Wat gaat er fout?
Heel graag een reactie op i.hirs@freepack.nl

**Comment by MarijndenHaan** [comment]
Bedankt voor je issue. Van wat ik kan zien uit de beschrijving is dat de input voor AdministrationCode (-a Freepack - API test) niet goed gaat. Wanneer een input spaties bevat moet het tussen aanhalingstekens staan, in dit geval dus -a "Freepack - API test". 
Daarnaast heb ik de code doorgelopen en kwam ik inderdaad langs een bug die deze opdracht stopte. Dit is nu opgelost in de nieuwe versie v0.0.8. Ik hoor graag of deze versie het probleem oplost.

Logfile wordt nog niet overal in de CLI ondersteund. Voor nu kunnen opdrachten uitgeprobeerd worden in een terminal (bv. dos-prompt) waar eventuele foutmeldingen getoond worden. Hiervoor gebruik je dezelfde opdrachten.

**Comment by inezhirs** [comment]
Dank voor je antwoord. Inmiddels had ik via de dos-opdrachtprompt al vastgesteld dat er quotes omheen moesten (zie #17). En hoe kan ik die nieuwe versie downloaden?

Met vriendelijke groet,
Inèz Hirs
Programmeur
[fpsmail]
Freepack Software B.V.
Wilhelminalaan 23
2405 EB  Alphen aan den Rijn
Tel:          0172-427027
E -mail:   ***@***.******@***.***>
Website: www.freepack.nl

Dit e-mailbericht is vertrouwelijk en inclusief eventuele bijlagen uitsluitend bestemd voor de geadresseerde. Gebruik van deze informatie door anderen dan de geadresseerde is verboden. Openbaarmaking, vermenigvuldiging, verspreiding en/of verstrekking van deze informatie aan derden is niet toegestaan. De afzender aanvaardt geen aansprakelijkheid voor enigerlei schade voortvloeiend uit virussen, verkeerd gebruik en/of ongeoorloofde acceptatie van de inhoud van dit bericht.

[Beschrijving: Beschrijving: ***@***.***CCB4F6.3CAD3300]



Van: MarijndenHaan ***@***.***
Verzonden: dinsdag 20 april 2021 15:43
Aan: blue-10/Blue10CLI ***@***.***>
CC: Inez Hirs ***@***.***>; Author ***@***.***>
Onderwerp: Re: [blue-10/Blue10CLI] het commando 'vendor create' lijkt niets te doen (#15)


Bedankt voor je issue. Van wat ik kan zien uit de beschrijving is dat de input voor AdministrationCode (-a Freepack - API test) niet goed gaat. Wanneer een input spaties bevat moet het tussen aanhalingstekens staan, in dit geval dus -a "Freepack - API test".
Daarnaast heb ik de code doorgelopen en kwam ik inderdaad langs een bug die deze opdracht stopte. Dit is nu opgelost in de nieuwe versie v0.0.8. Ik hoor graag of deze versie het probleem oplost.

Logfile wordt nog niet overal in de CLI ondersteund. Voor nu kunnen opdrachten uitgeprobeerd worden in een terminal (bv. dos-prompt) waar eventuele foutmeldingen getoond worden. Hiervoor gebruik je dezelfde opdrachten.

**Comment by MarijndenHaan** [comment]
De nieuwe versie is te downloaden hier op github.

De korte route: 
- https://github.com/blue-10/Blue10CLI/releases/tag/v0.0.8 
- Download de Blue10CLI.zip

De lange route (indien er weer een nieuwe versie uitkomt)
- https://github.com/blue-10/Blue10CLI (Homepage)
- Rechts staat kopje 'Releases'
- Daaronder is de nieuwste versie zichtbaar (op dit moment 'v0.0.8-Master-767315945-62')
- Klik daarop
- En download de Blue10CLI.zip

Er zijn twee mappen cli en headless. Gebruik de cli om terminal feedback te krijgen en de headless om dat niet te krijgen

**Comment by inezhirs** [comment]
Oké dank je wel.

Met vriendelijke groet,
Inèz Hirs
Programmeur
[fpsmail]
Freepack Software B.V.
Wilhelminalaan 23
2405 EB  Alphen aan den Rijn
Tel:          0172-427027
E -mail:   ***@***.******@***.***>
Website: www.freepack.nl

Dit e-mailbericht is vertrouwelijk en inclusief eventuele bijlagen uitsluitend bestemd voor de geadresseerde. Gebruik van deze informatie door anderen dan de geadresseerde is verboden. Openbaarmaking, vermenigvuldiging, verspreiding en/of verstrekking van deze informatie aan derden is niet toegestaan. De afzender aanvaardt geen aansprakelijkheid voor enigerlei schade voortvloeiend uit virussen, verkeerd gebruik en/of ongeoorloofde acceptatie van de inhoud van dit bericht.

[Beschrijving: Beschrijving: ***@***.***CCB4F6.3CAD3300]



Van: MarijndenHaan ***@***.***
Verzonden: dinsdag 20 april 2021 15:57
Aan: blue-10/Blue10CLI ***@***.***>
CC: Inez Hirs ***@***.***>; Author ***@***.***>
Onderwerp: Re: [blue-10/Blue10CLI] het commando 'vendor create' lijkt niets te doen (#15)


De nieuwe versie is te downloaden hier op github.

De korte route:

  *   https://github.com/blue-10/Blue10CLI/releases/tag/v0.0.8
  *   Download de Blue10CLI.zip

De lange route (indien er weer een nieuwe versie uitkomt)

  *   https://github.com/blue-10/Blue10CLI (Homepage)
  *   Rechts staat kopje 'Releases'
  *   Daaronder is de nieuwste versie zichtbaar (op dit moment 'v0.0.8-Master-767315945-62')
  *   Klik daarop
  *   En download de Blue10CLI.zip

Er zijn twee mappen cli en headless. Gebruik de cli om terminal feedback te krijgen en de headless om dat niet te krijgen

**Comment by inezhirs** [comment]
Ik heb versie 0.0.8 getest. Yasen had had een versie gestuurd waarin hij iets had gewijzigd waardoor de CLI uitgevoerd kon worden vanuit mijn cobol programma, tot nu toe werkte dat in elk geval voor de credentials check. Ik vermoed dat jouw wijziging op een andere versie is gedaan, want versie 0.0.8 wordt niet goed meer uitgevoerd vanuit mijn cobol programma; ik probeer de credentials check, maar hij blijft er in ‘hangen’.

Met vriendelijke groet,
Inèz Hirs
Programmeur
[fpsmail]
Freepack Software B.V.
Wilhelminalaan 23
2405 EB  Alphen aan den Rijn
Tel:          0172-427027
E -mail:   ***@***.******@***.***>
Website: www.freepack.nl

Dit e-mailbericht is vertrouwelijk en inclusief eventuele bijlagen uitsluitend bestemd voor de geadresseerde. Gebruik van deze informatie door anderen dan de geadresseerde is verboden. Openbaarmaking, vermenigvuldiging, verspreiding en/of verstrekking van deze informatie aan derden is niet toegestaan. De afzender aanvaardt geen aansprakelijkheid voor enigerlei schade voortvloeiend uit virussen, verkeerd gebruik en/of ongeoorloofde acceptatie van de inhoud van dit bericht.

[Beschrijving: Beschrijving: ***@***.***CCB4F6.3CAD3300]



Van: MarijndenHaan ***@***.***
Verzonden: dinsdag 20 april 2021 15:43
Aan: blue-10/Blue10CLI ***@***.***>
CC: Inez Hirs ***@***.***>; Author ***@***.***>
Onderwerp: Re: [blue-10/Blue10CLI] het commando 'vendor create' lijkt niets te doen (#15)


Bedankt voor je issue. Van wat ik kan zien uit de beschrijving is dat de input voor AdministrationCode (-a Freepack - API test) niet goed gaat. Wanneer een input spaties bevat moet het tussen aanhalingstekens staan, in dit geval dus -a "Freepack - API test".
Daarnaast heb ik de code doorgelopen en kwam ik inderdaad langs een bug die deze opdracht stopte. Dit is nu opgelost in de nieuwe versie v0.0.8. Ik hoor graag of deze versie het probleem oplost.

Logfile wordt nog niet overal in de CLI ondersteund. Voor nu kunnen opdrachten uitgeprobeerd worden in een terminal (bv. dos-prompt) waar eventuele foutmeldingen getoond worden. Hiervoor gebruik je dezelfde opdrachten.

**Comment by MarijndenHaan** [comment]
Er is overlegt en wij hebben wat aanpassingen gedaan zodat het weer zou moeten werken. Versie v0.0.9 https://github.com/blue-10/Blue10CLI/releases/tag/v0.0.9

Ik hoor graag of het werkt of niet.

**Comment by inezhirs** [comment]
Ja zeker; deze versie werkt weer! Dank.
Ik had net nog een mailtje verstuurd met een paar vragen. We blijven ze maar afvuren…

Met vriendelijke groet,
Inèz Hirs
Programmeur
[fpsmail]
Freepack Software B.V.
Wilhelminalaan 23
2405 EB  Alphen aan den Rijn
Tel:          0172-427027
E -mail:   ***@***.******@***.***>
Website: www.freepack.nl

Dit e-mailbericht is vertrouwelijk en inclusief eventuele bijlagen uitsluitend bestemd voor de geadresseerde. Gebruik van deze informatie door anderen dan de geadresseerde is verboden. Openbaarmaking, vermenigvuldiging, verspreiding en/of verstrekking van deze informatie aan derden is niet toegestaan. De afzender aanvaardt geen aansprakelijkheid voor enigerlei schade voortvloeiend uit virussen, verkeerd gebruik en/of ongeoorloofde acceptatie van de inhoud van dit bericht.

[Beschrijving: Beschrijving: ***@***.***CCB4F6.3CAD3300]



Van: MarijndenHaan ***@***.***
Verzonden: woensdag 21 april 2021 12:08
Aan: blue-10/Blue10CLI ***@***.***>
CC: Inez Hirs ***@***.***>; Author ***@***.***>
Onderwerp: Re: [blue-10/Blue10CLI] het commando 'vendor create' lijkt niets te doen (#15)


Er is overlegt en wij hebben wat aanpassingen gedaan zodat het weer zou moeten werken. Versie v0.0.9 https://github.com/blue-10/Blue10CLI/releases/tag/v0.0.9

Ik hoor graag of het werkt of niet.

**Comment by MarijndenHaan** [comment]
Dat is goed om te horen. Ja blijf ze zeker stellen!

**Comment by inezhirs** [comment]
Hallo Marijn,
Het is gelukt facturen te downloaden. Na verwerken probeer ik ze af te melden met de opdracht:
blue10cli.exe invoice sign -i <Blue10-ID van de factuur> -c <maar wat geef ik hier op?>
volgens de readme moet dat een grootboeknummer zijn, maar wat als er meer dan 1 factuurregel in de factuur voorkomt en dus meerdere grootboeknummers?
Als ik een factuur afmeld met achter –c het enige grootboeknummer dat ik heb aangemaakt in Blue10, dan zie ik de factuur bij opnieuw downloaden niet meer terug, maar dat is leuk als test, maar wat moet er dus opgegeven achter –c?
Als ik niks opgeef, dan worden de facturen steeds opnieuw gedownload met “invoice pull”
Waarom is er sowieso een grootboeknummer nodig? Is het niet voldoende de factuur af te melden met het Blue10-ID?

Met vriendelijke groet,
Inèz Hirs
Programmeur
[fpsmail]
Freepack Software B.V.
Wilhelminalaan 23
2405 EB  Alphen aan den Rijn
Tel:          0172-427027
E -mail:   ***@***.******@***.***>
Website: www.freepack.nl

Dit e-mailbericht is vertrouwelijk en inclusief eventuele bijlagen uitsluitend bestemd voor de geadresseerde. Gebruik van deze informatie door anderen dan de geadresseerde is verboden. Openbaarmaking, vermenigvuldiging, verspreiding en/of verstrekking van deze informatie aan derden is niet toegestaan. De afzender aanvaardt geen aansprakelijkheid voor enigerlei schade voortvloeiend uit virussen, verkeerd gebruik en/of ongeoorloofde acceptatie van de inhoud van dit bericht.

[Beschrijving: Beschrijving: ***@***.***CCB4F6.3CAD3300]



Van: MarijndenHaan ***@***.***
Verzonden: woensdag 21 april 2021 13:02
Aan: blue-10/Blue10CLI ***@***.***>
CC: Inez Hirs ***@***.***>; Author ***@***.***>
Onderwerp: Re: [blue-10/Blue10CLI] het commando 'vendor create' lijkt niets te doen (#15)


Dat is goed om te horen. Ja blijf ze zeker stellen!

**Comment by ghost** [comment]
`-c` in dit geval is `ledger-entry-code`: `The ledger entry code assigned to the invoice by the ERP system`.
Dit is niet de grootboeknummer maar de boekstuk nummer die gegeven wordt door de ERP aan een factuur.
Wanneer deze actie is uitgevoerd, is die verwerkt. Verwerkte facturen worden die niet meer getoond met `pull` of `peek`. omdat ze al klaar zijn.

**Comment by inezhirs** [comment]
..ledger-entry-code: The ledger entry code assigned to the invoice by the ERP system
Oké, maar waar haal ik die code vandaan? Kan ik 'm in de xml vinden?
Is het deze code soms: <Blue10Code>10001</Blue10Code>?

**Comment by ghost** [comment]
Die haal je uit je eigen boekhoudsysteem.

**Comment by inezhirs** [comment]
Oké duidelijk; ik dacht dat er een Blue10 nummer nodig was, maar ik stuur nu het door ons toegekende factuurnummer terug. Dat werkt. De factuur wordt niet meer opgehaald. Dank je wel.
Overigens valt het me op dat als ik hier tekst intik tussen kleiner-dan- en groter-dan-teken, dat die tekst verdwijnt. Ik tikte in bovenstaande vraag: Is het deze code soms: (Blue10Code)10001(/Blue10Code) waarbij ik nu die tekens maar even vervangen heb door ( en ).  Wijzig dat in kleiner dan en groter dan en die tekst valt weg als je de tekst plaatst; dan blijft alleen 10001 over .... vreemd toch?
