### ISSUE TITLE
Wijzigen van leverancier gegevens

### ISSUE THREAD

**Issue by inezhirs** [blue-10/Blue10CLI#26]
Via 'vendor create' zou ik de gegevens van een eerder ingevoerde leverancier moeten kunnen wijzigen. In de readme lees ik dat ik dan het Blue10-ID mee moet geven. Dat zou betekenen dat ik van elke aangemaakte leverancier het (erg lange) ID moet uitlezen uit  succeed_result.txt en in onze bestanden moet opslaan. Dat is nogal omslachtig. 
Wij willen gegevens kunnen wijzigen door ons eigen id mee te geven, door opnieuw de leverancier (of grootboeknummer of BTWcode) aan te leveren via create, op dezelfde manier als de eerste keer, maar met enkele gewijzigde gegevens.
Als ik dat nu doe voor een leverancier, dan krijg ik de melding: vendor already exists.

**Comment by ghost** [comment]
`Vendor create` is alleen het aanmaken van een nieuwe vendor, hiermee kunnen geen Vendors gewijzigd worden. Hiervoor voor je dan ook niet een Blue10-ID in.

Voor het aanpassen van al bestaande vendors gebruik de opdrachten `vendor list` en `vendor sync`. `list` haalt de lijst op van bestaande vendors, gebruik de `--query` optie om een gefilterde lijst te krijgen. De ouput van `list` kan gebruikt worden als input voor `sync`. Wijzig hierin de Vendors, Blue10-IDs staan er al gelijk bij, en met de `sync` opdracht worden de aanpassingen opgeslagen.

Het gebruik van Blue10-ID is nodig om in het BLue10 systeem te identificeren om welke Vendor het gaat. Dit kan niet met een eigen gegeven Id.
