### ISSUE TITLE
CLI sync command wijzigt bestaande blue10 gegevens niet

### ISSUE THREAD

**Issue by FreepackHarold** [blue-10/Blue10CLI#36]
Bij het uitvoeren van het vatcode (btwcode) en grootboekrekening (GLAccount) sync command in CLI worden bestaande gegevens niet gewijzigd. De cli reageert met de warning gegeven bestaat al. Volgens de documentatie zouden de gegevens wel aangepast moeten worden.

**Comment by MarijndenHaan** [comment]
Dankje voor je bericht. Ik heb even snel geprobeerd vatcodes te wijzigen en ik krijg geen warnings. 
Wat zegt de warning precies? Welk bestandsformaat gebruik je en welke gegevens van vatcode/GLAccount probeer je te wijzigen? Kan je een voorbeeld sync-data delen die niet werkt en de command die je gebruikt?

**Comment by FreepackHarold** [comment]
[BTWcodes.csv](https://github.com/blue-10/Blue10CLI/files/8305593/BTWcodes.csv)
Blue10CLI.exe vatcode sync -i btwcodes.csv --input-format csv

Bij deze opdracht krijg ik 6 warnings en 0 zijn er geimporteerd. Kan je dit naspelen?

**Comment by MarijndenHaan** [comment]
Ik zie dat je voor alle 6 een Empty Guid gebruikt op de Id. De CLI ziet dit als nieuwe vatcodes en daarvoor heeft die een unieke AdministrationCode nodig. De AdministrationCode bestaat dan al waardoor je de warning "Failed syncing VATCode 'xxxxx' - VatCode already exists" krijgt.

Om bestaande VatCodes te wijzigenen moet je de Id meegeven, deze krijg je mee met de command "vatcode list".

**Comment by FreepackHarold** [comment]
Bedankt! Je hebt gelijk. We gaan dit aanpassen.
