### ISSUE TITLE
Default kostenplaats wordt niet geaccepteerd

### ISSUE THREAD

**Issue by FreepackHarold** [blue-10/Blue10CLI#37]
Via een grootboekrekening kan een kostenplaats meegegeven worden aan Blue10. Als bij een factuurregel een grootboekrekening wordt gekozen welke een default kostenplaats heeft wordt deze ook gelijk getoond in Blue10. 
Echter het invoerveld van de kostenplaats kleurt rood. Blue10 accepteert de kostenplaats niet want de factuur staat niet klaar om opgehaald te worden door externe systeem. De kostenplaats kan gewijzigd worden, maar zal niet geaccepteerd worden.
Waarom accepteert Blue10 de kostenplaats niet?

**Comment by ydinkov** [comment]
De huidige CLI ondersteunt nog geen kostenposten of kostenplaatsen.
We nemen de ze ondersteuning mee in een toekomstige release. 

Ondertussen kan je wel via de Blue10 SDK wél kostenposten en kostenplaatsen aanmaken, verwijderen en updaten.
Of desnoods direct tegen de web api aanpraten om alvast CostCenters en CostUnits aan te maken
https://documenter.getpostman.com/view/884788/blue10-api/2Mtt6L#intro

**Comment by FreepackHarold** [comment]
Bedankt Yasen voor je terugkoppeling. Het zou erg handig zijn als we via CLI de kostenplaatsen kunnen uploaden. Uploaden via SDK en direct api gebruiken is geen oplossing voor ons.

In Blue10 online kunnen we nu bij een factuurregel geen kostenplaats opslaan. Komt dit omdat Blue10 controleert of de kostenplaats bekend is? Doordat de kostenplaatsen niet geupload kunnen worden via CLI werkt dit dus niet?
Uit de api documentatie begrijp ik dat kostenplaatsen geupload kunnen worden zonder koppeling met crediteur of grootboekrekening. Het is dus een losse lijst die aangeboden wordt bij de factuurregel in Blue10? Als de CLI straks kostenplaatsen kan uploaden kunnen wij dus bij een factuurregel elke kostenplaats kiezen die we willen. Klopt dit?

**Comment by ydinkov** [comment]
@FreepackHarold dat klopt. Na het eenmalig uploaden van kostenplaatsen, kunnen deze gekoppeld worden aan individuele factuurregels.

**Comment by FreepackHarold** [comment]
@ydinkov @MarijndenHaan  Ik zie dat jullie een nieuwe versie van CLI hebben gemaakt. Dat is snel. Echter is er nog geen documentatie over welke gegevens een kostenplaats  bevat. Zonder deze specificatie kan ik niet een sync actie doen. Ik kan wel een list actie doen. Het resultaat is uiteraard een lege lijst. Kunnen jullie de gegevens van een kostenplaats terugkoppelen?
Alvast bedankt.

**Comment by ydinkov** [comment]
@FreepackHarold Yes! Je houdt ons goed in de gaten  :D . Ik ga later deze week documentatie toevoegen. 

Tot dan zou je een soortgelijke lijst van objecten mee moeten geven als de GLAccounts

Voor CostUnit is dat:
```xml
<CostUnits>
  <CostUnit>
       <Name>...</Name> 
       <AdministrationCode>...</AdministrationCode> <!--Code zoals bekend ERP pakket-->
       <IdCompany>....</IdCompany> <!--Id van Blue10 Company-->
  </CostUnit>
  ...
</CostUnits>
```

Voor CostCenter is dat:
```xml
<CostCenters>
  <CostCenter>
         <Name>...</Name>
         <AdministrationCode>...</AdministrationCode>  <!--Code zoals bekend ERP pakket-->
         <IdCompany>....</IdCompany> <!--Id van Blue10 Company-->
  </CostCenter>
  ...
</CostCenters>
```

Eenmaal gesynct, krijgen de CostCenters/Units een `<Id>` en kan je ze met een `list` commando ophalen

**Comment by FreepackHarold** [comment]
Ja ik zit er een beetje op te wachten. :-D 
Ik heb een en ander geprobeerd maar ik kan geen goede sync uitvoeren. De volgende csv bevat de juiste kolommen, maar de error Unrecognized Guid format melding krijg ik:
Name,Id,AdministrationCode,IdCompany,LastUpdateDate
cc1,,000050,,
cc2,,000055,,

**Comment by MarijndenHaan** [comment]
Het formaat is goed alleen de sync functie in combinatie met .CSV bestanden verwacht in elk veld een waarde op Id en LastUpdateData. 
Het zou er dan als volgs uitzien:
```
Name,Id,AdministrationCode,IdCompany,LastUpdateDate
cc1,00000000-0000-0000-0000-000000000000,000050,(CompanyId),0001-01-01
cc2,00000000-0000-0000-0000-000000000000,000055,(CompanyId),0001-01-01
```
